name: MinecraftRevival
main: me.redstom.revival.plugin.RevivalPlugin
api-version: 1.19
author: RedsTom
version: 1.0
libraries:
  - org.xerial:sqlite-jdbc:3.40.1.0
  - org.reflections:reflections:0.10.2
commands:
  inventory: {}
  custom-give: {}